version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node
      - image: circleci/mysql:5.6.38-ram
    steps:
      - checkout

      - run:
          name: Install MySQL client
          command: |
            sudo apt-get update -y
            sudo apt-get install -y default-mysql-client

      - restore_cache:
          name: Restore Gems Dependencies Cache
          keys:
            - gems-dependencies-{{ checksum "Gemfile.lock" }}
            - gems-dependencies- # fallback to using the latest cache if no exact match is found

      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies
          command: |
            gem update --system
            gem install bundler
            bundle config --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
            npm install --cache vendor/npm

      - save_cache:
          name: Save Gems Dependencies Cache
          key: gems-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - save_cache:
          name: Save NPM Package Cache
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - vendor/npm

      - run:
          name: Copy Configuration Files
          command: |
            cp config/database{.sample,}.yml

      - run:
          name: Execute Tests
          command: bundle exec rspec
