version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node
      - image: circleci/mysql:5.6.38-ram
    steps:
      - checkout

      - run:
          name: Install MySQL client
          command: |
            apt-get update -y
            apt-get install -y mysql-client

      - restore_cache:
          name: Restore Gems Dependencies Cache
          keys:
            - gems-dependencies-{{ checksum "Gemfile.lock" }}
            - gems-dependencies- # fallback to using the latest cache if no exact match is found

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: |
            gem update --system
            gem install bundler
            bundle config --local path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
            yarn install --frozen-lockfile --cache-folder vendor/yarn

      - save_cache:
          name: Save Gems Dependencies Cache
          key: gems-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - save_cache:
        name: Save Yarn Package Cache
        key: yarn-packages-{{ checksum "yarn.lock" }}
        paths:
          - vendor/yarn

      - run:
        name: Copy Configuration Files
        command: |
          cp config/database{.sample,}.yml

      - run:
          name: Execute Tests
          command: bundle exec rspec
