default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: fustibus_development

test:
  <<: *default
  database: fustibus_test

production:
  <<: *default
  database: fustibus_production
  username: fustibus
  password: <%= ENV['FUSTIBUS_DATABASE_PASSWORD'] %>
